name: Lint

on: [push, pull_request]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  CLANG_FORMAT: clang-format-18
  CLANG_TIDY: clang-tidy-18

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Create Build Environment
      run: python3 .github/scripts/cmake.py mkdir --path ${{ runner.workspace }}/build

    - name: Download minimal cd image
      run: python3 .github/scripts/cmake.py minimal --output ${{ github.workspace }}/data/cd.iso

    - name: Install dependencies
      run: >
        python3 .github/scripts/cmake.py install
        --profile lint
        --extra-package ${{ env.CLANG_FORMAT }}
        --extra-package ${{ env.CLANG_TIDY }}

    - name: Configure CMake
      run: >
        python3 .github/scripts/cmake.py configure
        --source ${{ github.workspace }}
        --build-dir ${{ runner.workspace }}/build
        --build-type ${{ env.BUILD_TYPE }}
        --option=-DCLANG_FORMAT=${{ env.CLANG_FORMAT }}
        --option=-DCLANG_TIDY=${{ env.CLANG_TIDY }}

    - name: Setup lint range
      env:
        PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        PR_BASE_SHA: ${{ github.event.pull_request.base.sha }}
        PUSH_AFTER_SHA: ${{ github.event.after }}
        PUSH_BEFORE_SHA: ${{ github.event.before }}
      run: python3 .github/scripts/lint.py range

    - name: format lint
      run: python3 .github/scripts/lint.py format --build-dir ${{ runner.workspace }}/build --workspace ${{ github.workspace }}

    - name: clang-tidy lint
      env:
        BUILD_DIR: ${{ runner.workspace }}/build
      run: python3 .github/scripts/lint.py tidy

    - name: Upload failure logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: lint-logs
        if-no-files-found: warn
        path: |
          ${{ runner.workspace }}/build/CMakeFiles/CMakeOutput.log
          ${{ runner.workspace }}/build/CMakeFiles/CMakeError.log
